#!/bin/sh

GREEN='\033[0;32m'
LIGHTCYAN='\033[1;36m'
NC='\033[0m'

echo "${GREEN}Type your commit comment, followed by [ENTER]:${NC}"
# the read command stores the user input as a string
read comment
# the -e command enables the backslash necessary for colored text
echo "${GREEN}commit comment has been loaded${NC}"
# just a spacer
echo "${LIGHTCYAN}............${NC}"

echo "${GREEN}git add . started${NC}"
git add .
echo "${GREEN}git add . completed${NC}"
echo "${LIGHTCYAN}............${NC}"
echo "${GREEN}git commit -am started${NC}"
eval "git commit -am \"${comment}\""
echo "${GREEN}git commit -am completed${NC}"
echo "${LIGHTCYAN}............${NC}"
echo "${GREEN}git push started${NC}"
git push
git push github master
echo "${GREEN}git push completed${NC}"
echo "${LIGHTCYAN}............${NC}"

echo "${LIGHTCYAN}............${NC}"
echo "${GREEN}deployment complete!${NC}"

echo "${LIGHTCYAN}............${NC}"
echo "${GREEN}recording logs, please check the log file after completion${NC}"

echo "${LIGHTCYAN}............${NC}"
echo "${GREEN}log recording complete!${NC}"
